export const authConstants = {
  REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOAD_SUCCESS: "USER_LOAD_SUCCESS",
  LOAD_FAILURE: "USER_LOAD_FAILURE",

  LOGOUT: "USER_LOGOUT",
};
